In [2]:
import numpy as np
from numpy import ndarray
from math import log, sqrt
from typing import Callable
from functools import lru_cache

In [9]:
@lru_cache(maxsize=1)
def H_otimes_n(n: int) -> ndarray:
    r"""
    Retorna :math:`H^{\otimes n}`

    Args:
        n (int): numero de qubits
    """
    hadamard = np.array([[1, 1], [1, -1]]) #* (1 / (2 ** (1 / 2)))
    result = hadamard
    n -= 1  # primera iteración siempre inicia en hadamard, pero no cuenta como multiplicación

    for _ in range(n):
        result = np.tensordot(result, hadamard, axes=0)
    result = result.reshape(-1, result.shape[-1]) # Kronecker products crea submatrices, esto reshapes a matriz
    return result


In [10]:
def proyection_mean(n:int):
    N = 2**n
    op = np.ones(N)*(2/N)-np.eye(N)
    print(op)
    return op
    

In [11]:
def inversion_bout_mean(n:int) -> ndarray:
    op = np.matmul(H_otimes_n(n),proyection_mean(n))
    op = np.matmul(op,H_otimes_n(n))
    return op
    

In [12]:
def phase_inversion(n, f:Callable) -> ndarray:
    return np.eye(n)

In [20]:
def grover(N: int, f: Callable):
    """Función donde se implementa Grover's Algorithm

    Args:
        N (int): numero de estados
        f (Callable): funcion oráculo?
    """
    n = int(log(N, 2)) + 1  # Numero de qubits
    N = 2**n # Y QUÉ, HEWLETT PACKARDS
    psi_0 = np.ones((N,N))  # quantum state??????????????????????
    print(n,N,psi_0)
    psi_i = H_otimes_n(n) * psi_0  # inicialization
    print(psi_i)
    # sqrt(n) iteraciones
    for _ in range(int(sqrt(N))+1):
        psi_i = phase_inversion(n,f) * psi_i
        psi_i = inversion_bout_mean(n) * psi_i
    


In [19]:
N = 3

def f(x):
    return x == 2

grover(N, f)


2 4 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


ValueError: operands could not be broadcast together with shapes (8,2) (4,4) 